<?php
//FRANCES
$lang = array(
        "logfor" => "vous vous êtes connecté avec",
	"Log" => "Commencer la session",
        "username" => "Nom d'utilisateur",
        "password" => "le mot de passe",
        "Home" => "Accueil",
        "List" => "Lister",
        "Count" => "Compter",
        "Cart" => "Chariot",
        "Login" => "Connexion",
        "Return" => "Revenir",
        "id" => "Identifiant",
        "name" => "Nom",
        "descrip" => "La description",
        "price" => "Prix",
        "option" => "Les choix",
        "delete" => "Supprimer",
        "iva" => "T.V.A.",
        "sumTotal" => "Montant Total",
        "buy" => "acheter",
        "addPro" => "Ajouter un produit",
        "image" => "image",
        "Send" => "Envoyer",
        "ReturnList" => "Retour à la liste",
        "created" => "Créé le produit",
        "BuyPro" => "Acheter un produit",
        "GoShop" => "Aller à la boutique",
        "links" => "Liens",
        "Tougle" => "Langue",
	"quantity" => "Quantité",
)

?>
